//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Borer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_RIGHT_TIP                   101
#define IDPE_BULK                       102
#define IDD_FLATEDIT_DIALOG             102
#define IDD_OPEN_DELIM_DIALOG           103
#define IDPS_BULK                       104
#define IDPE_PACKET_SIZE                105
#define IDPS_SIZE                       106
#define IDPE_BUFFER                     107
#define IDPS_BUFFER                     108
#define IDMD_SYSTEM                     109
#define IDMT_SYSTEM                     110
#define IDMC_HARDWARE                   111
#define IDR_MAINFRAME                   112
#define IDR_MAINFRAME2                  112
#define IDR_BorerTYPE                   113
#define IDD_DQ_LOGIN                    114
#define IDB_BITMAP1                     115
#define IDR_RIGHT_COMM                  116
#define IDR_BIN_GOURD                   117
#define IDD_DLGAUTOSEND                 118
#define IDI_ICONIDLE                    119
#define IDC_BUTTON_GROUP                119
#define IDD_DLG_HPCFG                   120
#define IDI_ICONPRJ                     121
#define IDC_LIST_VWITEM                 121
#define IDI_ICONBUSY                    122
#define IDD_DIALOG_CFG                  123
#define IDB_EDIT_TREE                   124
#define IDI_ICONDEV                     125
#define IDI_ICONGRF                     126
#define IDR_RIGHT_GRAPH                 126
#define IDI_ICONNPAD                    127
#define IDB_DRAG_MULTI                  127
#define IDD_DLG_MSG                     128
#define IDB_DRAG_SINGLE                 129
#define IDC_DROP_COPY_ROOT              130
#define IDC_DROP_MOVE_ABOVE             131
#define IDC_DROP_COPY_ABOVE             132
#define IDD_DLGATPARA                   132
#define IDC_NODROP                      133
#define IDC_DROP_MOVE_ROOT              134
#define IDD_DLG_ATSET                   134
#define IDC_CURSOR1                     135
#define IDC_DROP_COPY_SON               136
#define IDC_DROP_MOVE_SON               137
#define IDR_RIGHT_CFGEDIT               137
#define IDD_DLG_TESTTASK                138
#define IDMT_TIPS                       139
#define IDI_ICON4                       140
#define IDC_CURSOR_POINT                140
#define IDD_DLG_INQUIRVAR               141
#define IDI_ICON3                       142
#define IDI_ICON2                       144
#define IDI_ICON1                       145
#define IDC_BN_WARNFILE                 145
#define IDR_TOOLBAR_SCRIPT              146
#define IDD_DLG_MESSGEBOX               147
#define IDR_TB_CSIRUN                   148
#define IDD_DLGMESSAGEPARA              149
#define IDD_DLG_BROWSER                 150
#define IDD_DIALOGTIMESLEEP             151
#define IDD_DIALOG1                     152
#define IDD_DLG_EDITMAP                 152
#define IDB_BUTTONS                     152
#define IDD_DLGHEADPATH                 153
#define IDR_RIGHT_PRJTREE               154
#define IDD_DLGMSGATTRIBUTE0            155
#define IDR_RIGHT_MAIN                  156
#define IDD_DLGMSGATTRIBUTE1            157
#define IDR_RIGHT_CFGTREE               157
#define IDD_DLGKEYATTRIBUTE0            158
#define IDD_DLGKEYATTRIBUTE             159
#define IDD_HANDSET                     160
#define IDD_HANDSET_SETUP               161
#define IDD_MAT_SETUP                   162
#define IDD_DLGTASK                     163
#define IDD_DLGVARIANT                  164
#define IDD_DLG_TRACETASK               165
#define IDMD_TIPS                       166
#define IDD_DLG_TRACEINFO               167
#define IDD_DLG_SYSTEMPARANEW2          169
#define IDD_DLG_SETVAR                  170
#define IDD_DLG_DELAYTIME               171
#define IDMC_HARDBROWSER                172
#define IDD_PCF_SETUP                   173
#define IDD_DQ_YOKE                     174
#define IDC_RADIOSENDMSG                175
#define IDC_DELIMITER                   176
#define IDC_LIST1                       177
#define IDC_STATIC_GROUP                178
#define IDC_RADIOWAITMSG                179
#define IDC_EDIT_ENDADDR                180
#define IDC_LIST_FLASH                  181
#define IDC_DESCRIPTION                 182
#define IDC_LIST_MAT                    183
#define IDC_RADIOIFWAITMSG              184
#define IDC_EDIT_FLASH_INDEX            185
#define IDC_LIST_DEFINEMSG              186
#define IDC_EDIT_FLASH_SIZE             187
#define IDC_BAUDCOMBO                   188
#define IDC_PARITYCOMBO                 189
#define IDC_COMBO_MAT_TYPE              190
#define IDC_ROLE_IT                     192
#define IDC_EDIT_MAT_INDEX              193
#define IDC_TREEHDPARA                  194
#define IDC_EDIT_MAT_VALUE              195
#define IDC_EDITPARA                    196
#define IDC_EDITSENDTIMES               197
#define IDC_EDIT_STARTADDR              198
#define IDC_EDIT_MAT_NAME               199
#define IDC_DATABITSCOMBO               200
#define IDC_EDITGETVALUE                201
#define IDC_EDIT_FLASH_NAME             202
#define IDC_TABMESSAGE                  203
#define IDC_EDIT_MAT_INDEX1             204
#define IDC_LISTTASK                    205
#define IDC_EDIT_FLASH_FILE             206
#define IDD_SET_ALIAS                   206
#define IDC_STOPBITSCOMBO               207
#define IDC_COMBO_MAT_VALUE             208
#define IDC_LISTTESTTASK                209
#define IDC_BUTTON_ADD                  210
#define IDC_EDITMSGNAME                 211
#define IDC_LISTVARIANT                 212
#define IDC_BUTTON_DEL                  213
#define IDC_COMBO_VAR                   214
#define IDC_BUTTON_BUILD                215
#define IDC_EDIT_ADDRESS                216
#define IDC_BUTTON_FILE                 217
#define IDCE_DQ_PASSWORD                218
#define IDC_EDIT_LEN                    219
#define IDC_TREEMSG                     220
#define IDC_EDIT_BOXCONTENT             221
#define IDC_LISTKEY                     222
#define IDCE_DQ_OFFICE                  223
#define IDC_LISTPOINT                   224
#define IDC_LISTTRACETASK               225
#define IDC_EDIT1                       226
#define IDC_EDIT_MCUMAP                 227
#define IDC_EDIT3                       227
#define IDC_EDITHEADPATH                228
#define IDC_EDIT4                       228
#define IDC_EDIT_KEEPTIME               229
#define IDC_EDIT5                       229
#define IDC_BUTTON1                     230
#define IDC_EDIT2                       231
#define IDC_BNOPENFILE                  231
#define IDC_EDIT_VALUE                  232
#define IDC_EDIT_MDMMAP                 233
#define IDC_BUTTON2                     234
#define IDC_TABDLG                      235
#define IDC_RADIO1                      236
#define IDC_BNSAVEFILE                  236
#define IDC_EDIT_DELAYTIME              237
#define IDC_RADIO2                      238
#define IDC_TREEBROWSER                 239
#define IDC_RADIO3                      240
#define IDC_CHECKON                     241
#define IDC_BTN_DISCARD                 241
#define IDC_HC_CONFIG                   242
#define IDC_BTNHEADPATH                 243
#define IDC_HC_CONAT                    243
#define IDC_RADIO4                      244
#define IDCE_DQ_AID                     245
#define IDR_RIGHT_LIST                  245
#define IDC_HC_CFBRS                    246
#define IDCE_DQ_VERSION                 247
#define IDC_HC_CFBAT                    247
#define IDE_CFG_FILE                    248
#define IDC_COMBOMESSAGENAME            249
#define IDE_CFG_ATFILE                  249
#define IDC_EDITMESSAGE                 250
#define IDC_EDITMSGCODE                 251
#define IDC_LCDBTN                      252
#define IDCE_DQ_USER                    253
#define IDC_LISTMSG                     254
#define IDC_OPENBMP                     255
#define IDC_EDITTIMESLEEP               256
#define IDC_OPENMASK                    257
#define IDC_BMPPATH                     258
#define IDC_MASKPATH                    259
#define IDC_COMBO                       260
#define IDC_LCD_X                       261
#define IDC_LCD_Y                       262
#define IDC_BEGINDRAW                   263
#define IDC_ENDDRAW                     264
#define IDC_STATICODE                   265
#define IDC_CANCELDRAW                  266
#define IDC_STATICNAME                  267
#define IDC_DELETEONEKEY                267
#define IDC_TAB                         268
#define IDC_COMMA                       269
#define IDC_OTHER                       270
#define XT_IDC_HSPLITBAR                271
#define XT_IDC_BTN_LEFT                 272
#define XT_IDC_BTN_RIGHT                273
#define XT_IDC_BTN_HOME                 274
#define XT_IDC_BTN_END                  275
#define IDC_TAB_DOCKINGVIEW             276
#define IDC_TAB_HIDE                    277
#define IDC_TAB_CLASSVIEW               278
#define IDC_TAB_RESOURCEVIEW            279
#define IDC_TAB_FILEVIEW                280
#define IDC_TAB_PROPERTIES              281
#define IDC_EXPAND_ALL_TREE             282
#define IDC_COUNT_SUBTREE               283
#define IDC_COUNT_ENTIRE_TREE           284
#define IDS_OLE_INIT_FAILED             285
#define XT_IDS_TIPTEXT                  286
#define ID_DQC_BROWSE                   287
#define IDD_DQ_COPY                     288
#define IDC_LISTCOVER                   288
#define IDCE_DQ_IMAGE                   289
#define IDD_DLG_REEXCUTEPDK             289
#define IDC_APPCFG_CONFIG               289
#define ID_START_TIPS                   290
#define IDC_COVER_WARN                  290
#define IDD_DLG_REGISTER                291
#define ID_COVER_START                  291
#define IDC_CURSOR_MOVE                 292
#define ID_STOP                         292
#define IDD_DLGMDMDEBUG                 293
#define IDC_LIST_ATEDIT                 293
#define IDD_DLG_ATSEND                  294
#define IDC_LIST_AT                     294
#define IDD_DLG_GOLINE                  295
#define IDD_IMPORTXML                   300
#define IDI_PDKIDLE                     301
#define IDD_DLGFLASHATTRIBUTE           301
#define IDI_PDKACT                      302
#define IDD_DLGMATATTRIBUTE             302
#define IDD_DLGPCFATTRIBUTE             303
#define IDD_DLG_CFG                     304
#define ID_START_WNDVERB                360
#define ID_START_TABVERB                370
#define ID_START_GRAPH                  380
#define IDC_DEBUGBAR                    390
#define IDMT_MDMDEBUG                   391
#define IDC_BUTTON3                     392
#define IDC_BUTTON4                     393
#define IDS_BUTTON1                     394
#define IDS_BUTTON2                     395
#define IDS_BUTTON3                     396
#define IDS_BUTTON4                     397
#define IDS_BUTTON5                     398
#define IDC_EDITCELL                    399
#define IDC_BTN_MODI                    1003
#define IDC_COMBO1                      1006
#define IDC_EDIT_SNR                    1007
#define IDC_COMBO2                      1007
#define IDC_EDIT_PWR                    1008
#define IDC_COMBO3                      1008
#define IDC_EDIT_SAVEFILE               1009
#define IDC_COMBO4                      1009
#define IDC_EDIT_WARNTIME               1010
#define IDC_CH_WARN                     1010
#define IDC_ST_WARNTIME                 1011
#define IDC_EDIT_FORMAT                 1011
#define IDC_EDITCOMMANDNAME             1011
#define IDC_ED_WARNTIME                 1012
#define IDC_EDITCOMMANDFORMAT           1012
#define IDC_ST_WARNWAV                  1013
#define IDC_EDITCOMMANDCAPTION          1013
#define IDCE_DQ_CONFIRM                 1014
#define IDC_ED_WARNWAV                  1014
#define IDC_EDIT_PARANUM                1014
#define IDC_EDIT_PARATYPE               1015
#define IDC_LIST_EDIT                   1016
#define IDC_EDIT_PARACAPTION            1016
#define IDC_EDIT_PARSE                  1017
#define IDC_BTN_ADD                     1019
#define IDC_BTN_DELETE                  1023
#define IDC_BTN_CLEARALL                1025
#define IDC_HC_CONFIGMCU                1028
#define IDC_HC_CFBRSMCU                 1030
#define IDE_CFG_FILEMCU                 1033
#define IDC_MAP_CONFIG                  1034
#define IDC_EDIT_ALIAS                  1036
#define IDC_EDITNAME                    1037
#define IDE_MAP_FILE                    1038
#define IDC_MAP_CFBRS                   1039
#define IDE_HO_FILE                     1040
#define IDE_PU_FILE                     1041
#define IDE_RELEASE_FILE                1042
#define IDC_HO_CFBRS                    1043
#define IDE_NODATA_WARNFILE             1044
#define IDC_RELEASE_CFBRS               1045
#define IDC_PU_CFBRS                    1046
#define IDC_NODATA_CFBRS                1047
#define IDE_SCANFREQ_FILE               1048
#define IDE_CHANGFREQ_FILE              1049
#define IDC_SCANFREQ_CFBRS              1050
#define IDC_CHANGEFREQ_CFBRS            1051
#define IDC_EDITCODE                    1058
#define IDC_EDIT_NAME                   1078
#define IDC_HANDCUR                     5005
#define ID_MDM_START                    32772
#define ID_RENAME                       32773
#define ID_MDM_STOP                     32774
#define ID_CALCULATE_LEVEL              32775
#define ID_COM_CFG                      32776
#define ID_COMTASK_CFG                  32777
#define ID_ADD_CHILD                    32778
#define IDRG_ZOOMOUT                    32778
#define ID_ADD_SIBLING                  32779
#define ID_SORT_SUBTREE_ALPHABETIC      32780
#define ID_SORT_SUBTREE_NUMERIC         32781
#define IDRC_ADDROW                     32782
#define ID_DATE_TIME                    32783
#define ID_DELETE_ITEM                  32784
#define IDRC_DELROW                     32784
#define ID_DELETE_ALL_ITEMS             32785
#define ID_PP_SELECTALL                 32786
#define ID_PP_CLEARALL                  32787
#define ID_EDIT_DISABLEBSATSOL          32790
#define IDRG_ZOOMIN                     32791
#define ID_EDIT_DISABLEDRAGANDDROP      32792
#define ID_READ_ONLY                    32793
#define ID_CSI_INIT                     32794
#define IDRG_BMP_SAVE                   32794
#define ID_CSI_RUN                      32795
#define IDRG_BMP_COPY                   32796
#define ID_PARA_OPEN                    32797
#define ID_PARA_ADD                     32798
#define ID_COLLAPSE_ALL_ENTIRE_TREE     32799
#define ID_PARA_DEL                     32800
#define ID_PARA_INSERT                  32801
#define ID_PARA_SAVE                    32802
#define ID_TREE_SAVE                    32803
#define ID_SCRIPT_BEGIN                 32804
#define ID_SCRIPT_END                   32805
#define ID_SCRIPT_MESSAGEBOX            32808
#define ID_SCRIPT_STRTRACE              32809
#define ID_SCRIPTTOOLBAR                32810
#define ID_SCRIPT_DEBUGBREAK            32811
#define ID_SCRIPT_MAINFRAME             32812
#define ID_CSI_DBG                      32813
#define ID_CSI_GO                       32814
#define ID_LST_ALL                      32814
#define ID_CSI_SO                       32815
#define ID_LST_HIDE                     32815
#define ID_CSI_STEPINTO                 32816
#define ID_COM_CFG5                     32817
#define ID_CFGV_SYNCH2                  32818
#define ID_FILE_LOAD                    32819
#define ID_PARA_KEYPOINT                32820
#define ID_TIEM_SET                     32821
#define ID_PaneTest                     32822
#define ID_ScriptTest                   32823
#define ID_SEND_PORT                    32825
#define ID_SEND_MEM                     32826
#define ID_MN_DELAYTIME                 32827
#define ID_AUTO_SEND                    32828
#define ID_CSI_STEPOVER                 32829
#define ID_CSI_STEPOUT                  32830
#define ID_CSI_RUNTOEND                 32831
#define ID_CSI_STOP                     32832
#define ID_TIP_SAVE                     32834
#define ID_SAVEFILEC                    32835
#define ID_FILESAVEAS                   32836
#define ID_CMD_SYSINFO                  32837
#define ID_CMD_SHOWINFO                 32838
#define ID_RUNBAR                       32839
#define ID_MENUHEADPATH                 32840
#define ID_PARA_MATSETUP                32841
#define ID_PARA_PCFSETUP                32842
#define ID_MENUITEMHELP                 32843
#define ID_FILE_NEWC                    32844
#define ID_ITP_CLOSE                    32845
#define ID_ITP_OPEN                     32846
#define ID_ITP_NEW                      32847
#define ID_ITP_SAVE                     32848
#define ID_ITP_SAVEAS                   32849
#define ID_ITP_EXECUTE                  32853
#define ID_ITP_BROWSE                   32854
#define ID_ADD_CCHILD                   32855
#define ID_CTRL_PDK                     32856
#define ID_PARA_SAVEAS                  32857
#define ID_CSI_QUIT                     32859
#define ID_SCRIPT_PDKREEXCUTE           32861
#define ID_ADD_CFGCHILD                 32862
#define ID_ADD_CFGSIBLING               32863
#define ID_PARA_CREATEFLASH             32864
#define ID_MDMBAR                       32867
#define IDRG_SET_ALIAS                  32871
#define ID_TIP_FONT                     32876
#define ID_EDIT_GOLINE                  32878
#define ID_CREATE_REPORT                32879
#define ID_WAITRESPONSE                 32880
#define IDM_RUNTEST                     32881
#define IDM_DEBUGTEST                   32882
#define ID_SEND_DATABASE                32883
#define ID_EDIT_TOGGLE_BLACKPOINT       32884
#define ID_EDIT_GOTO_NEXT_BREAKPOINT    32885
#define ID_EDIT_GOTO_PREV_BREAKPOINT    32886
#define ID_EDIT_CLEAR_ALL_BREAKPOINTS   32887
#define ID_ITP_CFGDELETE                32900

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        298
#define _APS_NEXT_COMMAND_VALUE         32888
#define _APS_NEXT_CONTROL_VALUE         295
#define _APS_NEXT_SYMED_VALUE           387
#endif
#endif
