//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
USEUNIT("..\..\main\G__setup.c");
USEUNIT("..\..\src\v6_debug.cxx");
USEUNIT("..\..\src\Apiif.cxx");
USEUNIT("..\..\src\v6_auxu.cxx");
USEUNIT("..\..\src\BaseCls.cxx");
USEUNIT("..\..\src\CallFunc.cxx");
USEUNIT("..\..\src\v6_cast.cxx");
USEUNIT("..\..\src\Class.cxx");
USEUNIT("..\..\src\DataMbr.cxx");
USEUNIT("..\..\src\Api.cxx");
USEUNIT("..\..\src\v6_input.cxx");
USEUNIT("..\..\src\v6_disp.cxx");
USEUNIT("..\..\src\v6_dump.cxx");
USEUNIT("..\..\src\v6_end.cxx");
USEUNIT("..\..\src\v6_error.cxx");
USEUNIT("..\..\src\v6_expr.cxx");
USEUNIT("..\..\src\cbstrm.cpp");
USEUNIT("..\..\src\v6_fread.cxx");
USEUNIT("..\..\src\v6_func.cxx");
USEUNIT("..\..\src\g__cfunc.c");
USEUNIT("..\..\src\v6_gcoll.cxx");
USEUNIT("..\..\src\v6_global1.cxx");
USEUNIT("..\..\src\v6_global2.cxx");
USEUNIT("..\..\src\v6_ifunc.cxx");
USEUNIT("..\..\src\v6_inherit.cxx");
USEUNIT("..\..\src\v6_init.cxx");
USEUNIT("..\..\src\v6_decl.cxx");
USEUNIT("..\..\src\v6_winnt.cxx");
USEUNIT("..\..\src\v6_loadfile.cxx");
USEUNIT("..\..\src\v6_macro.cxx");
USEUNIT("..\..\src\v6_malloc.cxx");
USEUNIT("..\..\src\Method.cxx");
USEUNIT("..\..\src\MethodAr.cxx");
USEUNIT("..\..\src\v6_new.cxx");
USEUNIT("..\..\src\v6_newlink.cxx");
USEUNIT("..\..\src\v6_oldlink.cxx");
USEUNIT("..\..\src\v6_opr.cxx");
USEUNIT("..\..\src\v6_parse.cxx");
USEUNIT("..\..\src\v6_pause.cxx");
USEUNIT("..\..\src\v6_pcode.cxx");
USEUNIT("..\..\src\v6_pragma.cxx");
USEUNIT("..\..\src\v6_quote.cxx");
USEUNIT("..\..\src\v6_scrupto.cxx");
USEUNIT("..\..\src\v6_shl.cxx");
USEUNIT("..\..\src\v6_sizeof.cxx");
USEUNIT("..\..\src\v6_stdstrct.cxx");
USEUNIT("..\..\src\v6_struct.cxx");
USEUNIT("..\..\src\v6_stub.cxx");
USEUNIT("..\..\src\v6_tmplt.cxx");
USEUNIT("..\..\src\Token.cxx");
USEUNIT("..\..\src\Type.cxx");
USEUNIT("..\..\src\v6_typedef.cxx");
USEUNIT("..\..\src\Typedf.cxx");
USEUNIT("..\..\src\v6_val2a.cxx");
USEUNIT("..\..\src\v6_value.cxx");
USEUNIT("..\..\src\v6_var.cxx");
USEUNIT("..\..\src\v6_intrpt.cxx");
//---------------------------------------------------------------------------
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
    return 1;
}
//---------------------------------------------------------------------------
